connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://iceberg-catalog:5432/iceberg
iceberg.jdbc-catalog.connection-user=${ENV:ICEBERG_CATALOG_USER}
iceberg.jdbc-catalog.connection-password=${ENV:ICEBERG_CATALOG_PASSWORD}
iceberg.jdbc-catalog.catalog-name=iceberg
iceberg.jdbc-catalog.default-warehouse-dir=s3://data-lakehouse-bronze/iceberg/
fs.native-s3.enabled=false
hive.s3.endpoint=http://localstack:4566
hive.s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
hive.s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
hive.s3.path-style-access=true
hive.s3.ssl.enabled=false
